-- =====================================================
-- 사용자 시스템 추가를 위한 데이터베이스 스키마 업데이트
-- =====================================================

-- 1. 사용자 시퀀스 생성
CREATE SEQUENCE SEQ_USER
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    CACHE 20;

-- 2. 사용자 테이블 생성
CREATE TABLE USERS (
    USER_ID NUMBER(20) PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    NICKNAME VARCHAR2(50),
    PROFILE_IMAGE VARCHAR2(500),
    MBTI_TYPE VARCHAR2(4),
    IS_ACTIVE CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGIN TIMESTAMP
);

-- 3. 기존 테이블에 USER_ID 컬럼 추가

-- COMMENTS 테이블에 USER_ID 추가
ALTER TABLE COMMENTS ADD USER_ID NUMBER(20);

-- TEST_RESULTS 테이블에 USER_ID 추가  
ALTER TABLE TEST_RESULTS ADD USER_ID NUMBER(20);

-- COMMENTS 테이블의 RESULT_ID를 NULL 허용으로 변경 (커뮤니티 댓글용)
ALTER TABLE COMMENTS MODIFY RESULT_ID NUMBER(10) NULL;

-- 4. 인덱스 생성
CREATE INDEX IDX_USERS_USERNAME ON USERS(USERNAME);
CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);
CREATE INDEX IDX_USERS_MBTI_TYPE ON USERS(MBTI_TYPE);
CREATE INDEX IDX_USERS_CREATED_AT ON USERS(CREATED_AT);
CREATE INDEX IDX_USERS_LAST_LOGIN ON USERS(LAST_LOGIN);

CREATE INDEX IDX_COMMENTS_USER_ID ON COMMENTS(USER_ID);
CREATE INDEX IDX_TEST_RESULTS_USER_ID ON TEST_RESULTS(USER_ID);

-- 5. 외래키 제약조건 추가 (선택사항 - 성능상 필요시)
-- ALTER TABLE COMMENTS ADD CONSTRAINT FK_COMMENTS_USER 
--     FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE SET NULL;

-- ALTER TABLE TEST_RESULTS ADD CONSTRAINT FK_TEST_RESULTS_USER 
--     FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE SET NULL;

-- 6. 사용자 테이블 업데이트 트리거
CREATE OR REPLACE TRIGGER TRG_USERS_UPDATE
    BEFORE UPDATE ON USERS
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- 7. 샘플 관리자 사용자 생성 (비밀번호: admin123)
-- BCrypt 해시 값: $2a$10$example... (실제 구현시 Spring에서 생성)
INSERT INTO USERS (
    USER_ID, USERNAME, EMAIL, PASSWORD_HASH, NICKNAME, 
    MBTI_TYPE, IS_ACTIVE
) VALUES (
    SEQ_USER.NEXTVAL, 
    'admin', 
    'admin@mbtitest.com', 
    '$2a$10$examplehashfromspring', 
    '관리자',
    'INTJ',
    'Y'
);

-- 8. 기존 데이터 정리 (선택사항)
-- 기존 익명 댓글들은 USER_ID가 NULL로 남겨둠
-- 향후 사용자들이 회원가입하면서 점차 회원 댓글로 전환

-- 변경사항 커밋
COMMIT;

-- 테이블 구조 확인
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME IN ('USERS', 'COMMENTS', 'TEST_RESULTS')
ORDER BY TABLE_NAME, COLUMN_ID;

-- 생성된 시퀀스 확인
SELECT SEQUENCE_NAME, LAST_NUMBER 
FROM USER_SEQUENCES 
WHERE SEQUENCE_NAME = 'SEQ_USER';

-- 인덱스 확인
SELECT INDEX_NAME, TABLE_NAME, COLUMN_NAME
FROM USER_IND_COLUMNS 
WHERE TABLE_NAME IN ('USERS', 'COMMENTS', 'TEST_RESULTS')
ORDER BY TABLE_NAME, INDEX_NAME;

SELECT '🎉 사용자 시스템 데이터베이스 스키마 업데이트 완료!' AS MESSAGE FROM DUAL;
