-- VIEW_LOGS 테이블의 MBTI_TYPE을 nullable로 변경
-- 이 스크립트는 데이터베이스에서 직접 실행해야 합니다.

-- Oracle DB의 경우:
ALTER TABLE VIEW_LOGS MODIFY (MBTI_TYPE VARCHAR2(4) NULL);

-- MySQL의 경우:
-- ALTER TABLE VIEW_LOGS MODIFY MBTI_TYPE VARCHAR(4) NULL;

-- PostgreSQL의 경우:
-- ALTER TABLE VIEW_LOGS ALTER COLUMN MBTI_TYPE DROP NOT NULL;

-- 기존 데이터에서 null 값을 'UNKNOWN'으로 업데이트
UPDATE VIEW_LOGS SET MBTI_TYPE = 'UNKNOWN' WHERE MBTI_TYPE IS NULL;

COMMIT;