-- COMMENTS 테이블의 COMMENT_TEXT 컬럼 수정
-- CLOB에서 VARCHAR2(1000)로 변경

-- 1. 임시 컬럼 생성
ALTER TABLE COMMENTS ADD COMMENT_TEXT_TEMP VARCHAR2(1000);

-- 2. 기존 데이터를 임시 컬럼으로 복사 (CLOB을 VARCHAR2로 변환)
UPDATE COMMENTS 
SET COMMENT_TEXT_TEMP = CASE 
    WHEN DBMS_LOB.GETLENGTH(COMMENT_TEXT) <= 1000 
    THEN DBMS_LOB.SUBSTR(COMMENT_TEXT, 1000, 1)
    ELSE DBMS_LOB.SUBSTR(COMMENT_TEXT, 1000, 1)
END
WHERE COMMENT_TEXT IS NOT NULL;

-- 3. 기존 컬럼 삭제
ALTER TABLE COMMENTS DROP COLUMN COMMENT_TEXT;

-- 4. 임시 컬럼의 이름을 원래 이름으로 변경
ALTER TABLE COMMENTS RENAME COLUMN COMMENT_TEXT_TEMP TO COMMENT_TEXT;

-- 5. NOT NULL 제약조건 추가
ALTER TABLE COMMENTS MODIFY COMMENT_TEXT VARCHAR2(1000) NOT NULL;

-- 변경 내용 커밋
COMMIT;

-- 테이블 구조 확인
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'COMMENTS' 
ORDER BY COLUMN_ID;
