-- =============================================
-- MBTI 테스트 사이트 Oracle DB 스키마
-- =============================================

-- 1. 시퀀스 생성
CREATE SEQUENCE SEQ_TEST_RESULT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_USER_STATS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_COMMENT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SHARE_LOG START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VIEW_LOG START WITH 1 INCREMENT BY 1;

-- 2. 테스트 결과 저장 테이블
CREATE TABLE TEST_RESULTS (
    RESULT_ID       NUMBER(10) DEFAULT SEQ_TEST_RESULT.NEXTVAL PRIMARY KEY,
    USER_IP         VARCHAR2(50),                       -- 사용자 IP (비회원용)
    USER_AGENT      VARCHAR2(500),                      -- 브라우저 정보
    MBTI_TYPE       VARCHAR2(4) NOT NULL,               -- MBTI 결과 (예: ENFP)
    CATEGORY_SCORES CLOB,                               -- JSON 형태의 각 카테고리별 점수
    ANSWER_DATA     CLOB,                               -- 전체 답변 데이터 (JSON)
    AI_ANALYSIS     CLOB,                               -- AI 분석 결과
    TEST_DURATION   NUMBER(10),                         -- 테스트 소요 시간 (초)
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. 사용자 통계 테이블 (전체 통계용)
CREATE TABLE USER_STATS (
    STATS_ID        NUMBER(10) DEFAULT SEQ_USER_STATS.NEXTVAL PRIMARY KEY,
    STAT_DATE       DATE DEFAULT CURRENT_DATE,          -- 통계 날짜
    TOTAL_TESTS     NUMBER(10) DEFAULT 0,               -- 총 테스트 수
    MBTI_ENFP       NUMBER(10) DEFAULT 0,               -- ENFP 수
    MBTI_ENFJ       NUMBER(10) DEFAULT 0,               -- ENFJ 수
    MBTI_ENTP       NUMBER(10) DEFAULT 0,               -- ENTP 수
    MBTI_ENTJ       NUMBER(10) DEFAULT 0,               -- ENTJ 수
    MBTI_ESFP       NUMBER(10) DEFAULT 0,               -- ESFP 수
    MBTI_ESFJ       NUMBER(10) DEFAULT 0,               -- ESFJ 수
    MBTI_ESTP       NUMBER(10) DEFAULT 0,               -- ESTP 수
    MBTI_ESTJ       NUMBER(10) DEFAULT 0,               -- ESTJ 수
    MBTI_INFP       NUMBER(10) DEFAULT 0,               -- INFP 수
    MBTI_INFJ       NUMBER(10) DEFAULT 0,               -- INFJ 수
    MBTI_INTP       NUMBER(10) DEFAULT 0,               -- INTP 수
    MBTI_INTJ       NUMBER(10) DEFAULT 0,               -- INTJ 수
    MBTI_ISFP       NUMBER(10) DEFAULT 0,               -- ISFP 수
    MBTI_ISFJ       NUMBER(10) DEFAULT 0,               -- ISFJ 수
    MBTI_ISTP       NUMBER(10) DEFAULT 0,               -- ISTP 수
    MBTI_ISTJ       NUMBER(10) DEFAULT 0,               -- ISTJ 수
    AVG_DURATION    NUMBER(8,2),                        -- 평균 테스트 시간
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. 댓글 시스템 테이블
CREATE TABLE COMMENTS (
    COMMENT_ID      NUMBER(10) DEFAULT SEQ_COMMENT.NEXTVAL PRIMARY KEY,
    RESULT_ID       NUMBER(10),                         -- 연결된 테스트 결과
    MBTI_TYPE       VARCHAR2(4) NOT NULL,               -- 댓글 작성자의 MBTI 타입
    NICKNAME        VARCHAR2(50),                       -- 닉네임 (선택)
    COMMENT_TEXT    VARCHAR2(1000) NOT NULL,            -- 댓글 내용
    USER_IP         VARCHAR2(50),                       -- 작성자 IP
    LIKES_COUNT     NUMBER(10) DEFAULT 0,               -- 좋아요 수
    IS_DELETED      CHAR(1) DEFAULT 'N',                -- 삭제 여부
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_COMMENT_RESULT FOREIGN KEY (RESULT_ID) 
        REFERENCES TEST_RESULTS(RESULT_ID) ON DELETE CASCADE
);

-- 5. 공유 로그 테이블 (SNS 공유 추적용)
CREATE TABLE SHARE_LOGS (
    SHARE_ID        NUMBER(10) DEFAULT SEQ_SHARE_LOG.NEXTVAL PRIMARY KEY,
    RESULT_ID       NUMBER(10),                         -- 공유된 테스트 결과
    SHARE_PLATFORM  VARCHAR2(20) NOT NULL,              -- 공유 플랫폼 (kakao, facebook, twitter, etc.)
    USER_IP         VARCHAR2(50),                       -- 공유한 사용자 IP
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SHARE_RESULT FOREIGN KEY (RESULT_ID) 
        REFERENCES TEST_RESULTS(RESULT_ID) ON DELETE CASCADE
);

-- 6. 페이지 뷰 로그 테이블
CREATE TABLE VIEW_LOGS (
    VIEW_ID         NUMBER(10) DEFAULT SEQ_VIEW_LOG.NEXTVAL PRIMARY KEY,
    PAGE_TYPE       VARCHAR2(20) NOT NULL,              -- 페이지 타입 (test, result, stats, etc.)
    MBTI_TYPE       VARCHAR2(4),                        -- 조회된 MBTI 타입 (해당되는 경우)
    USER_IP         VARCHAR2(50),                       -- 방문자 IP
    USER_AGENT      VARCHAR2(500),                      -- 브라우저 정보
    REFERER         VARCHAR2(500),                      -- 유입 경로
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 7. 인덱스 생성 (성능 최적화)
CREATE INDEX IDX_TEST_RESULTS_MBTI ON TEST_RESULTS(MBTI_TYPE);
CREATE INDEX IDX_TEST_RESULTS_DATE ON TEST_RESULTS(CREATED_AT);
CREATE INDEX IDX_TEST_RESULTS_IP ON TEST_RESULTS(USER_IP);

CREATE INDEX IDX_COMMENTS_MBTI ON COMMENTS(MBTI_TYPE);
CREATE INDEX IDX_COMMENTS_DATE ON COMMENTS(CREATED_AT);
CREATE INDEX IDX_COMMENTS_RESULT ON COMMENTS(RESULT_ID);

CREATE INDEX IDX_SHARE_LOGS_PLATFORM ON SHARE_LOGS(SHARE_PLATFORM);
CREATE INDEX IDX_SHARE_LOGS_DATE ON SHARE_LOGS(CREATED_AT);

CREATE INDEX IDX_VIEW_LOGS_PAGE ON VIEW_LOGS(PAGE_TYPE);
CREATE INDEX IDX_VIEW_LOGS_DATE ON VIEW_LOGS(CREATED_AT);

-- 8. 기본 통계 데이터 삽입
INSERT INTO USER_STATS (STAT_DATE, TOTAL_TESTS) VALUES (CURRENT_DATE, 0);

-- 9. 트리거 생성 (자동 통계 업데이트)
CREATE OR REPLACE TRIGGER TRG_UPDATE_STATS
AFTER INSERT ON TEST_RESULTS
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    -- 오늘 날짜의 통계 레코드가 있는지 확인
    SELECT COUNT(*) INTO v_count 
    FROM USER_STATS 
    WHERE STAT_DATE = CURRENT_DATE;
    
    -- 없으면 생성
    IF v_count = 0 THEN
        INSERT INTO USER_STATS (STAT_DATE, TOTAL_TESTS) 
        VALUES (CURRENT_DATE, 0);
    END IF;
    
    -- 통계 업데이트
    UPDATE USER_STATS 
    SET 
        TOTAL_TESTS = TOTAL_TESTS + 1,
        UPDATED_AT = CURRENT_TIMESTAMP,
        -- MBTI 타입별 카운트 증가
        MBTI_ENFP = CASE WHEN :NEW.MBTI_TYPE = 'ENFP' THEN MBTI_ENFP + 1 ELSE MBTI_ENFP END,
        MBTI_ENFJ = CASE WHEN :NEW.MBTI_TYPE = 'ENFJ' THEN MBTI_ENFJ + 1 ELSE MBTI_ENFJ END,
        MBTI_ENTP = CASE WHEN :NEW.MBTI_TYPE = 'ENTP' THEN MBTI_ENTP + 1 ELSE MBTI_ENTP END,
        MBTI_ENTJ = CASE WHEN :NEW.MBTI_TYPE = 'ENTJ' THEN MBTI_ENTJ + 1 ELSE MBTI_ENTJ END,
        MBTI_ESFP = CASE WHEN :NEW.MBTI_TYPE = 'ESFP' THEN MBTI_ESFP + 1 ELSE MBTI_ESFP END,
        MBTI_ESFJ = CASE WHEN :NEW.MBTI_TYPE = 'ESFJ' THEN MBTI_ESFJ + 1 ELSE MBTI_ESFJ END,
        MBTI_ESTP = CASE WHEN :NEW.MBTI_TYPE = 'ESTP' THEN MBTI_ESTP + 1 ELSE MBTI_ESTP END,
        MBTI_ESTJ = CASE WHEN :NEW.MBTI_TYPE = 'ESTJ' THEN MBTI_ESTJ + 1 ELSE MBTI_ESTJ END,
        MBTI_INFP = CASE WHEN :NEW.MBTI_TYPE = 'INFP' THEN MBTI_INFP + 1 ELSE MBTI_INFP END,
        MBTI_INFJ = CASE WHEN :NEW.MBTI_TYPE = 'INFJ' THEN MBTI_INFJ + 1 ELSE MBTI_INFJ END,
        MBTI_INTP = CASE WHEN :NEW.MBTI_TYPE = 'INTP' THEN MBTI_INTP + 1 ELSE MBTI_INTP END,
        MBTI_INTJ = CASE WHEN :NEW.MBTI_TYPE = 'INTJ' THEN MBTI_INTJ + 1 ELSE MBTI_INTJ END,
        MBTI_ISFP = CASE WHEN :NEW.MBTI_TYPE = 'ISFP' THEN MBTI_ISFP + 1 ELSE MBTI_ISFP END,
        MBTI_ISFJ = CASE WHEN :NEW.MBTI_TYPE = 'ISFJ' THEN MBTI_ISFJ + 1 ELSE MBTI_ISFJ END,
        MBTI_ISTP = CASE WHEN :NEW.MBTI_TYPE = 'ISTP' THEN MBTI_ISTP + 1 ELSE MBTI_ISTP END,
        MBTI_ISTJ = CASE WHEN :NEW.MBTI_TYPE = 'ISTJ' THEN MBTI_ISTJ + 1 ELSE MBTI_ISTJ END
    WHERE STAT_DATE = CURRENT_DATE;
END;
/

-- 10. 업데이트 트리거 (UPDATED_AT 자동 업데이트)
CREATE OR REPLACE TRIGGER TRG_TEST_RESULTS_UPDATE
BEFORE UPDATE ON TEST_RESULTS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_COMMENTS_UPDATE
BEFORE UPDATE ON COMMENTS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_USER_STATS_UPDATE
BEFORE UPDATE ON USER_STATS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- 스키마 생성 완료!
-- 다음 명령어로 실행: @schema.sql
